flask:
  env: $ENV{FLASK_ENV, dev}
app:
  secret_key: $ENV{APP_SECRET_KEY, random_string_dss}
  database_url: $ENV{DATABASE_URL, postgresql://postgres@postgres/postgres}
  stub_source_data: $ENV{STUB_SOURCE_DATA, True}
sso:
  base_url: $ENV{SSO_URL, https://sso.trade.gov.uk}
  profile_path: $ENV{ACCESS_TOKEN_PATH, /api/v1/user/me/}
  authorize_path: $ENV{AUTHORIZE_PATH, /o/authorize/}
  access_token_path: $ENV{SSO_PATH_USER, /o/token/}
  logout_path: $ENV{SSO_PATH_LOGOUT, /logout/}
  client_id: $ENV{ABC_CLIENT_ID, sso_client_id}
  client_secret: $ENV{ABC_CLIENT_SECRET, sso_client_secret}
access_control:
  hawk_enabled: $ENV{AC_HAWK_ENABLED, True}
  hawk_nonce_enabled: $ENV{AC_HAWK_NONCE_ENABLED, True}
  hawk_response_header: $ENV{AC_HAWK_RESPONSE_HEADER, True}
  hawk_algorithm: $ENV{AC_HAWK_ALGORITHM, sha256}
  hawk_accept_untrusted_content: $ENV{AC_HAWK_ACCEPT_UNTRUSTED_CONTENT, False}
  hawk_localtime_offset_in_seconds: $ENV{AC_HAWK_LOCALTIME_OFFSET_IN_SECONDS, 0}
  hawk_timestamp_skew_in_seconds: $ENV{AC_HAWK_TIMESTAMP_SKEW_IN_SECONDS, 60}
session:
  secret_key: $ENV{SESSION_SECRET_KEY, _dss_authbroker_token}
