"""add indices to tariff table

Revision ID: b1395ef0c894
Revises: e61160a7d500
Create Date: 2020-04-21 16:35:11.194269

"""
import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.sql.schema import quoted_name  # noqa: F401


from app.db.models import get_schemas

revision = 'b1395ef0c894'
down_revision = 'e61160a7d500'


def create_schemas():
    conn = op.get_bind()
    for schema_name in get_schemas():
        if not conn.dialect.has_schema(conn, schema_name):
            conn.execute(sa.schema.CreateSchema(schema_name))


def upgrade():
    create_schemas()
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'L1_partner_idx',
        'L1',
        ['partner'],
        unique=False,
        schema=quoted_name('world_bank.tariff', quote=True),
        postgresql_using='hash',
    )
    op.create_index(
        'L1_product_idx',
        'L1',
        ['product'],
        unique=False,
        schema=quoted_name('world_bank.tariff', quote=True),
        postgresql_using='hash',
    )
    op.create_index(
        'L1_reporter_idx',
        'L1',
        ['reporter'],
        unique=False,
        schema=quoted_name('world_bank.tariff', quote=True),
        postgresql_using='hash',
    )
    op.create_index(
        'L1_year_idx',
        'L1',
        ['year'],
        unique=False,
        schema=quoted_name('world_bank.tariff', quote=True),
        postgresql_using='hash',
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'L1_year_idx', table_name='L1', schema=quoted_name('world_bank.tariff', quote=True)
    )
    op.drop_index(
        'L1_reporter_idx', table_name='L1', schema=quoted_name('world_bank.tariff', quote=True)
    )
    op.drop_index(
        'L1_product_idx', table_name='L1', schema=quoted_name('world_bank.tariff', quote=True)
    )
    op.drop_index(
        'L1_partner_idx', table_name='L1', schema=quoted_name('world_bank.tariff', quote=True)
    )
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
