"""Add not null constraints

Revision ID: 6922c3bf8667
Revises: 2b191e85239a
Create Date: 2020-04-17 16:02:25.757355

"""
import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.sql.schema import quoted_name  # noqa: F401


from app.db.models import get_schemas

revision = '6922c3bf8667'
down_revision = '2b191e85239a'


def create_schemas():
    conn = op.get_bind()
    for schema_name in get_schemas():
        if not conn.dialect.has_schema(conn, schema_name):
            conn.execute(sa.schema.CreateSchema(schema_name))


def upgrade():
    create_schemas()
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'application',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application',
        'case_closed_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application',
        'case_type',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application',
        'initial_processing_time',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'amendment_closed_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'case_processing_time',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'case_type',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'report_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'start_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'approve_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'batch_ref',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'status',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote',
        'status',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'start_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'dest_country_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'goods_item_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'inc_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'report_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'start_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'type',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'version_no',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'case_type',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'incorporation_flag',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'licence_conversion_flag',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'mil_flag',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'other_flag',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'report_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'start_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'status',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'temporary_licence_flag',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'torture_flag',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'type',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'country_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'country_name',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'mf_grp_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'start_datetime',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'display_text',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'footnote_type',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'mf_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'single_footnote_text',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'start_datetime',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ogl_type',
        'start_datetime',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ogl_type',
        'title',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ref_ars_subject',
        'ars_subject',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ref_country_mapping',
        'country_name',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'created_datetime',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'el_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'licence_type',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'status',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'country_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'start_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'country_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'start_date',
        existing_type=sa.DATE(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ultimate_end_user',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'start_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'country_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'start_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'country_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'status',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'licence_type',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'el_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'created_datetime',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'returns',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ref_country_mapping',
        'country_name',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ref_ars_subject',
        'ars_subject',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ogl_type',
        'title',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ogl_type',
        'start_datetime',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'start_datetime',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'single_footnote_text',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'mf_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'footnote_type',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'display_text',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'start_datetime',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'mf_grp_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'country_name',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'country_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'type',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'torture_flag',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'temporary_licence_flag',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'status',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'start_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'report_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'other_flag',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'mil_flag',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'licence_conversion_flag',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'incorporation_flag',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'case_type',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'version_no',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'type',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'start_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'report_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'inc_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'goods_item_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'dest_country_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'status_control',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'start_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'ela_grp_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote',
        'status',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'status',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'batch_ref',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'approve_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'start_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'report_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'case_type',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'case_processing_time',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'amendment_closed_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application',
        'initial_processing_time',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application',
        'case_type',
        existing_type=sa.TEXT(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application',
        'case_closed_date',
        existing_type=sa.DATE(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application',
        'batch_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
