"""world bank tariff eu part rate and eu rep rate added

Revision ID: 49e6f321ee08
Revises: db2ffee4a768
Create Date: 2020-04-09 11:59:42.967488

"""
import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.sql.schema import quoted_name  # noqa: F401


from app.db.models import get_schemas

revision = '49e6f321ee08'
down_revision = 'db2ffee4a768'


def create_schemas():
    conn = op.get_bind()
    for schema_name in get_schemas():
        if not conn.dialect.has_schema(conn, schema_name):
            conn.execute(sa.schema.CreateSchema(schema_name))


def upgrade():
    create_schemas()
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'L1',
        sa.Column('eu_part_rate', sa.Numeric(), nullable=True),
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.add_column(
        'L1',
        sa.Column('eu_rep_rate', sa.Numeric(), nullable=True),
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.alter_column(
        'L1',
        'partner',
        existing_type=sa.INTEGER(),
        type_=sa.Text(),
        existing_nullable=True,
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.alter_column(
        'L1',
        'reporter',
        existing_type=sa.INTEGER(),
        type_=sa.Text(),
        existing_nullable=True,
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'L1',
        'reporter',
        existing_type=sa.Text(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.alter_column(
        'L1',
        'partner',
        existing_type=sa.Text(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.drop_column('L1', 'eu_rep_rate', schema=quoted_name('world_bank.tariff', quote=True))
    op.drop_column('L1', 'eu_part_rate', schema=quoted_name('world_bank.tariff', quote=True))
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
