"""Change date to datetime

Revision ID: be326fe4f9e4
Revises: ccbdd5946d2e
Create Date: 2020-04-17 16:34:27.519885

"""
import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.sql.schema import quoted_name  # noqa: F401


from app.db.models import get_schemas

revision = 'be326fe4f9e4'
down_revision = 'ccbdd5946d2e'


def create_schemas():
    conn = op.get_bind()
    for schema_name in get_schemas():
        if not conn.dialect.has_schema(conn, schema_name):
            conn.execute(sa.schema.CreateSchema(schema_name))


def upgrade():
    create_schemas()
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'application',
        'case_closed_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'amendment_closed_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'report_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'start_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'approve_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'end_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'release_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'staging_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'start_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'end_user',
        'start_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'start_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'report_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'start_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'report_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'start_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'end_datetime',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'start_datetime',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'end_datetime',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'start_datetime',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ogl_type',
        'end_datetime',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ogl_type',
        'start_datetime',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'return',
        'created_datetime',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'return',
        'return_period_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'start_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ultimate_end_user',
        'start_date',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ultimate_end_user',
        'start_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'third_party',
        'start_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'return',
        'return_period_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'return',
        'created_datetime',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ogl_type',
        'start_datetime',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'ogl_type',
        'end_datetime',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'start_datetime',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_detail',
        'end_datetime',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'start_datetime',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'media_footnote_country',
        'end_datetime',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'start_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'incident',
        'report_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'start_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'goods_incident',
        'report_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'footnote_entry',
        'start_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'end_user',
        'start_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'start_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'staging_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'release_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'end_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'batch',
        'approve_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'start_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_country',
        'report_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application_amendment',
        'amendment_closed_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    op.alter_column(
        'application',
        'case_closed_date',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema=quoted_name('spire', quote=True),
    )
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
