"""Add all SPIRE tables

Revision ID: 2b191e85239a
Revises: 49e6f321ee08
Create Date: 2020-04-17 10:24:12.306828

"""
import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.sql.schema import quoted_name  # noqa: F401


from app.db.models import get_schemas

revision = '2b191e85239a'
down_revision = '49e6f321ee08'


def create_schemas():
    conn = op.get_bind()
    for schema_name in get_schemas():
        if not conn.dialect.has_schema(conn, schema_name):
            conn.execute(sa.schema.CreateSchema(schema_name))


def upgrade():
    create_schemas()
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'batch',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('batch_ref', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('approve_date', sa.Date(), nullable=True),
        sa.Column('release_date', sa.Date(), nullable=True),
        sa.Column('staging_date', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'country_group',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'end_user',
        sa.Column('eu_id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('ela_grp_id', sa.Integer(), nullable=True),
        sa.Column('end_user_type', sa.Text(), nullable=True),
        sa.Column('country_id', sa.Integer(), nullable=True),
        sa.Column('end_user_count', sa.Integer(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('status_control', sa.Text(), nullable=True),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('eu_id', 'version_number'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'footnote',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'media_footnote',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'media_footnote_country',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ela_grp_id', sa.Integer(), nullable=True),
        sa.Column('mf_grp_id', sa.Integer(), nullable=True),
        sa.Column('country_id', sa.Integer(), nullable=True),
        sa.Column('country_name', sa.Text(), nullable=True),
        sa.Column('status_control', sa.Text(), nullable=True),
        sa.Column('start_datetime', sa.Date(), nullable=True),
        sa.Column('end_datetime', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'ogl_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('start_datetime', sa.Date(), nullable=True),
        sa.Column('end_datetime', sa.Date(), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=True),
        sa.Column('f680_flag', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'ref_ars_subject',
        sa.Column('ars_value', sa.Text(), nullable=False),
        sa.Column('ars_subject', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('ars_value'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'ref_country_mapping',
        sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('country_name', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('country_id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'ref_do_not_report_value',
        sa.Column('dnr_type', sa.Text(), nullable=False),
        sa.Column('dnr_value', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('dnr_type', 'dnr_value'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'ref_report_ratings',
        sa.Column('rating', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('rating'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'application',
        sa.Column('ela_grp_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('case_type', sa.Text(), nullable=True),
        sa.Column('case_sub_type', sa.Text(), nullable=True),
        sa.Column('initial_processing_time', sa.Integer(), nullable=True),
        sa.Column('case_closed_date', sa.Date(), nullable=True),
        sa.Column('withheld_status', sa.Text(), nullable=True),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.Column('ela_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['spire.batch.id'],
        ),
        sa.PrimaryKeyConstraint('ela_grp_id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'country_group_entry',
        sa.Column('cg_id', sa.Integer(), nullable=False),
        sa.Column('country_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cg_id'],
            ['spire.country_group.id'],
        ),
        sa.PrimaryKeyConstraint('cg_id', 'country_id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'media_footnote_detail',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mf_id', sa.Integer(), nullable=True),
        sa.Column('status_control', sa.Text(), nullable=True),
        sa.Column('start_datetime', sa.Date(), nullable=True),
        sa.Column('end_datetime', sa.Date(), nullable=True),
        sa.Column('footnote_type', sa.Text(), nullable=True),
        sa.Column('display_text', sa.Text(), nullable=True),
        sa.Column('single_footnote_text', sa.Text(), nullable=True),
        sa.Column('joint_footnote_text', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['mf_id'],
            ['spire.media_footnote.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'returns',
        sa.Column('elr_id', sa.Integer(), nullable=False),
        sa.Column('elr_version', sa.Integer(), nullable=False),
        sa.Column('status', sa.Text(), nullable=True),
        sa.Column('created_datetime', sa.Date(), nullable=True),
        sa.Column('status_control', sa.Text(), nullable=True),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.Column('licence_type', sa.Text(), nullable=True),
        sa.Column('el_id', sa.Integer(), nullable=True),
        sa.Column('ogl_id', sa.Integer(), nullable=True),
        sa.Column('return_period_date', sa.Date(), nullable=True),
        sa.Column('end_country_id', sa.Integer(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('end_user_type', sa.Text(), nullable=True),
        sa.Column('eco_comment', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['spire.batch.id'],
        ),
        sa.PrimaryKeyConstraint('elr_id', 'elr_version'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'application_amendment',
        sa.Column('ela_grp_id', sa.Integer(), nullable=False),
        sa.Column('ela_id', sa.Integer(), nullable=False),
        sa.Column('case_type', sa.Text(), nullable=True),
        sa.Column('case_sub_type', sa.Text(), nullable=True),
        sa.Column('case_processing_time', sa.Integer(), nullable=True),
        sa.Column('amendment_closed_date', sa.Date(), nullable=True),
        sa.Column('withheld_status', sa.Text(), nullable=True),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['ela_grp_id'],
            ['spire.application.ela_grp_id'],
        ),
        sa.PrimaryKeyConstraint('ela_grp_id', 'ela_id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'application_country',
        sa.Column('ela_grp_id', sa.Integer(), nullable=False),
        sa.Column('country_id', sa.Integer(), nullable=False),
        sa.Column('report_date', sa.Date(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['spire.batch.id'],
        ),
        sa.ForeignKeyConstraint(
            ['ela_grp_id'],
            ['spire.application.ela_grp_id'],
        ),
        sa.PrimaryKeyConstraint('ela_grp_id', 'country_id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'footnote_entry',
        sa.Column('fne_id', sa.Integer(), nullable=False),
        sa.Column('fn_id', sa.Integer(), nullable=True),
        sa.Column('ela_grp_id', sa.Integer(), nullable=True),
        sa.Column('goods_item_id', sa.Integer(), nullable=True),
        sa.Column('country_id', sa.Integer(), nullable=True),
        sa.Column('fnr_id', sa.Integer(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('version_no', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.Column('status_control', sa.Text(), nullable=True),
        sa.Column('mfd_id', sa.Integer(), nullable=True),
        sa.Column('mf_grp_id', sa.Integer(), nullable=True),
        sa.Column('mf_free_text', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['spire.batch.id'],
        ),
        sa.ForeignKeyConstraint(
            ['ela_grp_id'],
            ['spire.application.ela_grp_id'],
        ),
        sa.ForeignKeyConstraint(
            ['fn_id'],
            ['spire.footnote.id'],
        ),
        sa.ForeignKeyConstraint(
            ['mfd_id'],
            ['spire.media_footnote_detail.id'],
        ),
        sa.PrimaryKeyConstraint('fne_id', 'version_no'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'goods_incident',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('inc_id', sa.Integer(), nullable=True),
        sa.Column('type', sa.Text(), nullable=True),
        sa.Column('goods_item_id', sa.Integer(), nullable=True),
        sa.Column('dest_country_id', sa.Integer(), nullable=True),
        sa.Column('source_country_grp_id', sa.Integer(), nullable=True),
        sa.Column('report_date', sa.Date(), nullable=True),
        sa.Column('ela_grp_id', sa.Integer(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('version_no', sa.Integer(), nullable=True),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.Column('status_control', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['spire.batch.id'],
        ),
        sa.ForeignKeyConstraint(
            ['ela_grp_id'],
            ['spire.application.ela_grp_id'],
        ),
        sa.ForeignKeyConstraint(
            ['source_country_grp_id'],
            ['spire.country_group.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'incident',
        sa.Column('inc_id', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.Text(), nullable=True),
        sa.Column('type', sa.Text(), nullable=True),
        sa.Column('case_type', sa.Text(), nullable=True),
        sa.Column('case_sub_type', sa.Text(), nullable=True),
        sa.Column('ela_grp_id', sa.Integer(), nullable=True),
        sa.Column('ela_id', sa.Integer(), nullable=True),
        sa.Column('licence_id', sa.Integer(), nullable=True),
        sa.Column('report_date', sa.Date(), nullable=True),
        sa.Column('temporary_licence_flag', sa.Integer(), nullable=True),
        sa.Column('licence_conversion_flag', sa.Integer(), nullable=True),
        sa.Column('incorporation_flag', sa.Integer(), nullable=True),
        sa.Column('mil_flag', sa.Integer(), nullable=True),
        sa.Column('other_flag', sa.Integer(), nullable=True),
        sa.Column('torture_flag', sa.Integer(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('version_no', sa.Integer(), nullable=False),
        sa.Column('ogl_id', sa.Integer(), nullable=True),
        sa.Column('status_control', sa.Text(), nullable=True),
        sa.Column('else_id', sa.Integer(), nullable=True),
        sa.Column('stakeholders_confirmed', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['spire.batch.id'],
        ),
        sa.ForeignKeyConstraint(
            ['ela_grp_id'],
            ['spire.application.ela_grp_id'],
        ),
        sa.PrimaryKeyConstraint('inc_id', 'version_no'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'third_party',
        sa.Column('tp_id', sa.Integer(), nullable=False),
        sa.Column('ela_grp_id', sa.Integer(), nullable=True),
        sa.Column('sh_id', sa.Integer(), nullable=True),
        sa.Column('country_id', sa.Integer(), nullable=True),
        sa.Column('ultimate_end_user_flag', sa.Integer(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('version_no', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.Column('status_control', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['spire.batch.id'],
        ),
        sa.ForeignKeyConstraint(
            ['ela_grp_id'],
            ['spire.application.ela_grp_id'],
        ),
        sa.PrimaryKeyConstraint('tp_id', 'version_no'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'ultimate_end_user',
        sa.Column('ueu_id', sa.Integer(), nullable=False),
        sa.Column('ela_grp_id', sa.Integer(), nullable=True),
        sa.Column('country_id', sa.Integer(), nullable=True),
        sa.Column('status_control', sa.Text(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('version_no', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.Column('sh_id', sa.Integer(), nullable=True),
        sa.Column('ultimate_end_user_flag', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['spire.batch.id'],
        ),
        sa.ForeignKeyConstraint(
            ['ela_grp_id'],
            ['spire.application.ela_grp_id'],
        ),
        sa.PrimaryKeyConstraint('ueu_id', 'version_no'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'ars',
        sa.Column('gi_id', sa.Integer(), nullable=False),
        sa.Column('ars_value', sa.Text(), nullable=False),
        sa.Column('ars_quantity', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['gi_id'],
            ['spire.goods_incident.id'],
        ),
        sa.PrimaryKeyConstraint('gi_id', 'ars_value'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'control_entry',
        sa.Column('gi_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Text(), nullable=False),
        sa.Column('value', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['gi_id'],
            ['spire.goods_incident.id'],
        ),
        sa.ForeignKeyConstraint(
            ['rating'],
            ['spire.ref_report_ratings.rating'],
        ),
        sa.PrimaryKeyConstraint('gi_id', 'rating'),
        schema=quoted_name('spire', quote=True),
    )
    op.create_table(
        'reason_for_refusal',
        sa.Column('gi_id', sa.Integer(), nullable=False),
        sa.Column('reason_for_refusal', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['gi_id'],
            ['spire.goods_incident.id'],
        ),
        sa.PrimaryKeyConstraint('gi_id', 'reason_for_refusal'),
        schema=quoted_name('spire', quote=True),
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reason_for_refusal', schema=quoted_name('spire', quote=True))
    op.drop_table('control_entry', schema=quoted_name('spire', quote=True))
    op.drop_table('ars', schema=quoted_name('spire', quote=True))
    op.drop_table('ultimate_end_user', schema=quoted_name('spire', quote=True))
    op.drop_table('third_party', schema=quoted_name('spire', quote=True))
    op.drop_table('incident', schema=quoted_name('spire', quote=True))
    op.drop_table('goods_incident', schema=quoted_name('spire', quote=True))
    op.drop_table('footnote_entry', schema=quoted_name('spire', quote=True))
    op.drop_table('application_country', schema=quoted_name('spire', quote=True))
    op.drop_table('application_amendment', schema=quoted_name('spire', quote=True))
    op.drop_table('returns', schema=quoted_name('spire', quote=True))
    op.drop_table('media_footnote_detail', schema=quoted_name('spire', quote=True))
    op.drop_table('country_group_entry', schema=quoted_name('spire', quote=True))
    op.drop_table('application', schema=quoted_name('spire', quote=True))
    op.drop_table('ref_report_ratings', schema=quoted_name('spire', quote=True))
    op.drop_table('ref_do_not_report_value', schema=quoted_name('spire', quote=True))
    op.drop_table('ref_country_mapping', schema=quoted_name('spire', quote=True))
    op.drop_table('ref_ars_subject', schema=quoted_name('spire', quote=True))
    op.drop_table('ogl_type', schema=quoted_name('spire', quote=True))
    op.drop_table('media_footnote_country', schema=quoted_name('spire', quote=True))
    op.drop_table('media_footnote', schema=quoted_name('spire', quote=True))
    op.drop_table('footnote', schema=quoted_name('spire', quote=True))
    op.drop_table('end_user', schema=quoted_name('spire', quote=True))
    op.drop_table('country_group', schema=quoted_name('spire', quote=True))
    op.drop_table('batch', schema=quoted_name('spire', quote=True))
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
