"""update transformed tariffs table

Revision ID: 98c763a4dca4
Revises: edb4f0469686
Create Date: 2020-05-18 09:56:58.656962

"""
import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.sql.schema import quoted_name  # noqa: F401


from app.db.models import get_schemas

revision = '98c763a4dca4'
down_revision = 'edb4f0469686'


def create_schemas():
    conn = op.get_bind()
    for schema_name in get_schemas():
        if not conn.dialect.has_schema(conn, schema_name):
            conn.execute(sa.schema.CreateSchema(schema_name))


def upgrade():
    create_schemas()
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'L1',
        sa.Column('eu_eu_rate', sa.Numeric(), nullable=True),
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.alter_column(
        'L1',
        'partner',
        existing_type=sa.TEXT(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.alter_column(
        'L1',
        'reporter',
        existing_type=sa.TEXT(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.drop_column('L1', 'country_average', schema=quoted_name('world_bank.tariff', quote=True))
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'L1',
        sa.Column('country_average', sa.NUMERIC(), autoincrement=False, nullable=True),
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.alter_column(
        'L1',
        'reporter',
        existing_type=sa.Integer(),
        type_=sa.TEXT(),
        existing_nullable=True,
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.alter_column(
        'L1',
        'partner',
        existing_type=sa.Integer(),
        type_=sa.TEXT(),
        existing_nullable=True,
        schema=quoted_name('world_bank.tariff', quote=True),
    )
    op.drop_column('L1', 'eu_eu_rate', schema=quoted_name('world_bank.tariff', quote=True))
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
